.PHONY: clean All

All:
	@echo "----------Building project:[ Debit_BDD - Debug ]----------"
	@cd "Debit_BDD" && "$(MAKE)" -f  "Debit_BDD.mk"
clean:
	@echo "----------Cleaning project:[ Debit_BDD - Debug ]----------"
	@cd "Debit_BDD" && "$(MAKE)" -f  "Debit_BDD.mk" clean
