.PHONY: clean All

All:
	@echo "----------Building project:[ Projet-ERP - Debug ]----------"
	@cd "Projet-ERP" && "$(MAKE)" -f  "Projet-ERP.mk"
clean:
	@echo "----------Cleaning project:[ Projet-ERP - Debug ]----------"
	@cd "Projet-ERP" && "$(MAKE)" -f  "Projet-ERP.mk" clean
