.PHONY: clean All

All:
	@echo "----------Building project:[ Actionner - Debug ]----------"
	@cd "Actionner" && "$(MAKE)" -f  "Actionner.mk"
clean:
	@echo "----------Cleaning project:[ Actionner - Debug ]----------"
	@cd "Actionner" && "$(MAKE)" -f  "Actionner.mk" clean
