.PHONY: clean All

All:
	@echo "----------Building project:[ Connexion_BDD - Debug ]----------"
	@cd "Connexion_BDD" && "$(MAKE)" -f  "Connexion_BDD.mk"
clean:
	@echo "----------Cleaning project:[ Connexion_BDD - Debug ]----------"
	@cd "Connexion_BDD" && "$(MAKE)" -f  "Connexion_BDD.mk" clean
